server:
  servlet:
    context-path: /client
  port: 8080

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org:
      springframework:
        web: info

authorization:
  server:
    url: http://localhost:9500

democlient:
  client-id: demo-client-jwt
  redirect-uri: http://localhost:8080/client/callback
  pkce: false
  authorization:
    endpoint: ${authorization.server.url}/oauth2/authorize
    response-type: code
    scope:
      - openid
      - profile
      - offline_access
  token:
    endpoint: ${authorization.server.url}/oauth2/token
    client-secret: demo-client-jwt-secret
  introspection:
    endpoint: ${authorization.server.url}/oauth2/introspect
  userinfo:
    endpoint: ${authorization.server.url}/userinfo
  resource:
    endpoint: http://localhost:9090/api/messages
  exchange:
    client-id: demo-client-token-exchange
    client-secret: demo-client-token-exchange-secret
    audience: exchanged-token
    scope:
      - openid
      - profile
      - email
